// Variáveis dinâmicas dos modelos de documento/prontuário do Sonatta.
// Os tokens correspondem aos campos reais das entidades do app (Client, Company,
// Professional, MedicalRecord, Test, Sale, Quote, Contract, Rental) e seguem o
// mesmo padrão já usado nos templates de WhatsApp e contratos do sistema.
export const VARIABLE_GROUPS = [
  {
    group: 'Data & Sistema',
    items: [
      { token: '{{ current_date }}', label: 'Data atual' },
      { token: '{{ current_date_long }}', label: 'Data por extenso' },
      { token: '{{ current_time }}', label: 'Hora atual' },
      { token: '{{ user_name }}', label: 'Usuário logado' },
      { token: '{{ user_role }}', label: 'Papel do usuário' },
    ],
  },
  {
    group: 'Cliente',
    items: [
      { token: '{{ client_name }}', label: 'Nome completo' },
      { token: '{{ client_cpf }}', label: 'CPF' },
      { token: '{{ client_phone }}', label: 'Telefone / WhatsApp' },
      { token: '{{ client_email }}', label: 'E-mail' },
      { token: '{{ client_birth_date }}', label: 'Data de nascimento' },
      { token: '{{ client_address }}', label: 'Endereço completo' },
      { token: '{{ client_cep }}', label: 'CEP' },
      { token: '{{ client_neighborhood }}', label: 'Bairro' },
      { token: '{{ client_city }}', label: 'Cidade' },
      { token: '{{ client_state }}', label: 'UF' },
      { token: '{{ client_payer_name }}', label: 'Responsável pelo pagamento' },
      { token: '{{ client_payer_document }}', label: 'CPF/CNPJ do responsável' },
      { token: '{{ client_usage }}', label: 'Uso dos aparelhos' },
      { token: '{{ client_referral }}', label: 'Profissional que indicou' },
    ],
  },
  {
    group: 'Clínica',
    items: [
      { token: '{{ company_name }}', label: 'Nome / Razão social' },
      { token: '{{ company_cnpj }}', label: 'CNPJ' },
      { token: '{{ company_address }}', label: 'Endereço' },
      { token: '{{ contact_phone }}', label: 'Telefone' },
      { token: '{{ company_email }}', label: 'E-mail' },
    ],
  },
  {
    group: 'Profissional',
    items: [
      { token: '{{ professional_name }}', label: 'Nome do profissional' },
      { token: '{{ professional_specialty }}', label: 'Especialidade' },
      { token: '{{ professional_council }}', label: 'Conselho (CRM/CRFa)' },
      { token: '{{ professional_phone }}', label: 'WhatsApp' },
    ],
  },
  {
    group: 'Atendimento / Prontuário',
    items: [
      { token: '{{ record_date }}', label: 'Data do atendimento' },
      { token: '{{ record_type }}', label: 'Tipo de atendimento' },
      { token: '{{ record_complaint }}', label: 'Queixa principal' },
      { token: '{{ record_notes }}', label: 'Anotações / evolução' },
      { token: '{{ record_audiogram_notes }}', label: 'Observações audiológicas' },
      { token: '{{ record_next_steps }}', label: 'Conduta / próximos passos' },
    ],
  },
  {
    group: 'Teste & Aparelhos',
    items: [
      { token: '{{ test_number }}', label: 'Nº do teste' },
      { token: '{{ device_name }}', label: 'Aparelho' },
      { token: '{{ device_serial }}', label: 'Nº de série' },
      { token: '{{ devices_list }}', label: 'Aparelhos testados' },
      { token: '{{ start_date }}', label: 'Início do teste' },
      { token: '{{ start_time }}', label: 'Hora de início' },
      { token: '{{ end_date }}', label: 'Término do teste' },
      { token: '{{ end_time }}', label: 'Hora de término' },
      { token: '{{ test_referral }}', label: 'Profissional que indicou' },
      { token: '{{ warranty }}', label: 'Garantia do aparelho' },
    ],
  },
  {
    group: 'Venda & Pagamentos',
    items: [
      { token: '{{ sale_number }}', label: 'Nº da venda' },
      { token: '{{ sale_date }}', label: 'Data da venda' },
      { token: '{{ sale_seller }}', label: 'Vendedor' },
      { token: '{{ sale_status }}', label: 'Status da venda' },
      { token: '{{ sale_balance }}', label: 'Saldo pendente' },
      { token: '{{ product_list }}', label: 'Produto' },
      { token: '{{ products_list }}', label: 'Lista de produtos' },
      { token: '{{ subtotal }}', label: 'Subtotal' },
      { token: '{{ discount }}', label: 'Desconto' },
      { token: '{{ total }}', label: 'Total da venda' },
      { token: '{{ payments_list }}', label: 'Formas de pagamento' },
    ],
  },
  {
    group: 'Orçamento & Contrato',
    items: [
      { token: '{{ quote_number }}', label: 'Nº do orçamento' },
      { token: '{{ contract_date }}', label: 'Data do contrato' },
      { token: '{{ total_value }}', label: 'Valor total' },
      { token: '{{ discount_value }}', label: 'Valor do desconto' },
      { token: '{{ discount_percent }}', label: 'Desconto (%)' },
      { token: '{{ installments_count }}', label: 'Nº de parcelas' },
      { token: '{{ installment_value }}', label: 'Valor da parcela' },
      { token: '{{ first_payment_date }}', label: '1º vencimento' },
      { token: '{{ payment_day }}', label: 'Dia de pagamento' },
    ],
  },
  {
    group: 'Locação',
    items: [
      { token: '{{ rental_number }}', label: 'Nº da locação' },
      { token: '{{ rental_product }}', label: 'Aparelho locado' },
      { token: '{{ rental_serial }}', label: 'Nº de série' },
      { token: '{{ rental_term_type }}', label: 'Prazo da locação' },
      { token: '{{ rental_start_date }}', label: 'Início da locação' },
      { token: '{{ rental_end_date }}', label: 'Término previsto' },
      { token: '{{ rental_monthly_amount }}', label: 'Valor mensal' },
      { token: '{{ rental_due_day }}', label: 'Dia de vencimento' },
      { token: '{{ rental_status }}', label: 'Status da locação' },
    ],
  },
];